# Homework #1 - The Linear Model

Matric Number: A0113598X

Email: a0113598@u.nus.edu

### General Notes about this assignment 

Hi, thanks for grading.

### Files included with this submission

#### hw1-1.ipynb
Solutions to programming questions

#### essay-1.pdf
Solutions to essay questions


## Programming Exercise 1

In [2]:
import numpy as np
import numpy.random as nr
import matplotlib.pyplot as pl
%matplotlib inline
# Plotting with style! 
import seaborn as sb 

# Size the plot appropriately for online display
pl.rcParams['figure.figsize'] = (12.0, 10.0)

Let's fix the random number generator first, in case we need results that are replicable.

In [3]:
nr.seed(3244)

In [4]:
#    Write your solution to the programming assignment here.  We've suggested some cells that you can add 
#    to your notebook as single line comments below.
#    Please place all of your cells to be run in a linear, unintervened order, such that we can automate
#    the running and grading of the assignment.

# load datasets code
from io import StringIO

def read_data_file(file_name):
	f = open(file_name, "r")
	mat = np.loadtxt(StringIO(f.read()))
	X = mat[:, :-1]
	y = np.matrix(mat[:, -1]).T
	return (X, y)

X_train, Y_train = read_data_file("hw1-train.dat")
N, M = X_train.shape

X_test, Y_test = read_data_file("hw1-test.dat")

# LR code

def lr(xn, yn, w, eta, index=-1):
	'''
	    Input: 
	        xn : Data points
	        yn : Classification of the previous data points, an Nx1 vector. 
	        w  : initial weight
	        eta : step size
	        index: index of the datapoint chosen, -1 means it will be random
	    Output: 
	        w : updated weight
	'''
	N = xn.shape[0]
	if index == -1: # stochastic
	    index = nr.randint(N)
	x = xn[index, :]
	y = yn[index]
	g = y * x / (1 + np.exp(y * (x.dot(w))))
	w = w + eta * g.T
	return w
    
# Evaluation code

# calculate the in sample error given w
def calculate_error(xn, yn, w):
	N = xn.shape[0]
	e = np.sum(np.log(1 + np.exp(np.multiply(-yn, (np.dot(xn, w)))))) / N
	# print(e)
	return e

# sigmoid function which can be applied to a vector
def sigmoid(s):
	exp_s = np.exp(s)
	return np.divide(exp_s, (1 + exp_s))

# calculates the E_out given data, classification, and weights
def out_error(xn, yn, w):
	N = xn.shape[0]
	prediction = (sigmoid(np.dot(xn, w)) > 0.5)
	real_class = (yn > 0)
	e = np.sum(prediction != real_class) / N
	return e

def evaluate_stochastic(eta, iteration):
	'''
		Run SGD using X_train and Y_train
		Input:
			eta: step size
			iteration: number of iteration of SGD
		output:
			w : final weights
			E_out: Error for out samples using X_test and Y_test
	'''
	w = np.zeros([M, 1])
	for i in range(iteration):
	    # calculate_error(X_train, Y_train, w)
	    w = lr(X_train, Y_train, w, eta, -1)
	E_out = out_error(X_test, Y_test, w)
	return (w, E_out)

def evaluate_deterministic(eta, iteration):
	'''
		Run deterministic gradient descent using X_train and Y_train
		Input:
			eta: step size
			iteration: number of iteration of gradient descent
		output:
			w : final weights
			E_out: Error for out samples using X_test and Y_test
	'''
	w = np.zeros([M, 1])
	for i in range(iteration):
		# calculate_error(X_train, Y_train, w)
		w = lr(X_train, Y_train, w, eta, i % N)
	E_out = out_error(X_test, Y_test, w)
	return (w, E_out)


In [5]:
# part a
w, E_out = evaluate_stochastic(0.05, 2333)
print("a: eta = 0.05, T = 2333")
print("Eventual weight vector:")
print(w)
print("E_out:", E_out, "\n")

a: eta = 0.05, T = 2333
Eventual weight vector:
[[-0.77103986]
 [ 0.69686794]
 [-0.71068577]
 [ 0.18921361]
 [-1.11267433]
 [ 0.23775555]
 [ 0.96439839]
 [-0.76712115]
 [ 0.36149172]
 [ 1.17128657]
 [ 0.34709316]
 [-1.01241315]
 [-0.6790299 ]
 [ 0.72990107]
 [ 1.16332397]
 [ 1.09742592]
 [-1.67913442]
 [ 1.31748317]
 [-0.63821407]
 [-1.11995321]]
E_out: 0.222333333333 



In [15]:
# part b
w, E_out = evaluate_stochastic(0.005, 2333)
print("b: eta = 0.005, T = 2333")
print("Eventual weight vector:")
print(w)
print("E_out:", E_out, "\n")

b: eta = 0.005, T = 2333
Eventual weight vector:
[[-0.09335889]
 [ 0.20215719]
 [-0.23996357]
 [-0.04251637]
 [-0.20440963]
 [ 0.03846584]
 [ 0.23017485]
 [-0.23390801]
 [ 0.07161958]
 [ 0.34289685]
 [ 0.07072517]
 [-0.16405645]
 [-0.07940969]
 [ 0.21138679]
 [ 0.22592153]
 [ 0.27787995]
 [-0.27183798]
 [ 0.27196301]
 [-0.15302842]
 [-0.17871196]]
E_out: 0.260333333333 



In [16]:
# part c1
w, E_out = evaluate_deterministic(0.05, 2333)
print("c1: eta = 0.05, T = 2333, deterministic")
print("Eventual weight vector:")
print(w)
print("E_out:", E_out, "\n")

c1: eta = 0.05, T = 2333, deterministic
Eventual weight vector:
[[-0.72940019]
 [ 0.85990151]
 [-1.15873921]
 [-0.05888132]
 [-1.12459694]
 [-0.06295276]
 [ 1.0753553 ]
 [-0.93569624]
 [ 0.41119313]
 [ 1.3961822 ]
 [ 0.16606345]
 [-0.79805704]
 [-0.70404885]
 [ 0.84129845]
 [ 1.11757352]
 [ 1.28384704]
 [-1.48376652]
 [ 1.39995501]
 [-0.65636591]
 [-1.08186501]]
E_out: 0.218 



In [11]:
# part c2
w, E_out = evaluate_deterministic(0.005, 2333)
print("c2: eta = 0.05, T = 2333, deterministic")
print("Eventual weight vector:")
print(w)
print("E_out:", E_out, "\n")

c2: eta = 0.05, T = 2333, deterministic
Eventual weight vector:
[[-0.13112574]
 [ 0.17243183]
 [-0.23161184]
 [-0.0007156 ]
 [-0.24678354]
 [ 0.00547271]
 [ 0.20750785]
 [-0.1796379 ]
 [ 0.08506787]
 [ 0.30888347]
 [ 0.03572705]
 [-0.14519921]
 [-0.10807148]
 [ 0.1878487 ]
 [ 0.2478724 ]
 [ 0.26941629]
 [-0.31270712]
 [ 0.27810743]
 [-0.13817623]
 [-0.2213296 ]]
E_out: 0.194666666667 



## Statement of Individual Work

Please initial (between the square brackets) one of the following statements.

[ZYC] I, A0113598X, certify that I have followed the CS 3244 Machine Learning class guidelines for homework assignments.  In particular, I expressly vow that I have followed the Facebook rule in discussing with others in doing the assignment and did not take notes (digital or printed) from the discussions.  

[ ] I, <*substitute your matric number here*>, did not follow the class rules regarding the homework assignment, because of the following reason:

<*Please fill in*>

I suggest that I should be graded as follows:

<*Please fill in*>

### References

I have refered to the following list of people and websites in preparing my homework submission:

I googled for some numpy and latex syntax